### ISSUE TITLE
Events won't work on IE8

### ISSUE THREAD

**Issue by mkoehler2911** [eXon/videojs-vimeo#12]
Hi! 
I wanted to play and pause vimeo videos with videojs events (play(), pause()).
Everything works fine on chrome, firefox, opera, safari and ie 9-11. But on ie8 these events won't work for vimeo.

Please help!
Thanks

**Comment by themicp** [comment]
I was facing the same problem and I found out that the iframe's onLoad event was never triggered on IE8 for some reason.
I created a PR fixing this: https://github.com/eXon/videojs-vimeo/pull/41 which I believe fixes your problems too.
