### ISSUE TITLE
Switching between Vimeo and Youtube.

### ISSUE THREAD

**Issue by massivebam** [eXon/videojs-vimeo#15]
Hi eXon,
This is not really and issue but more of a question.
I'm using your videojs-vimeo and videojs-youtube plugins together and I'm trying to switch between Vimeo and Youtube videos.
I tried several ways and short of disposing of it and re-initializing it, I haven't been very successful.

Among other things, I've tried to set the techOrder in the <video> tag to ["vimeo", "youtube"] and that didn't work (only the first type would play).

I also tried several variations of:
          _V_("projects_video").options.techOrder = [newType];
          _V_("projects_video").src(newURL);
and
          _V_("projects_video").src({ type: "video/"+newType, src:newURL });

Where newType is "vimeo" or "youtube".

So my question is, how would I go about changing the techOrder to load the Vimeo or Youtube videos short of disposing/reinitialize .
Thanks!

**Comment by pgtaboada** [comment]
Same here. It was my understanding, that a plugin should only try to play if it matches the url. But both youtube and vimeo plugins play the source no matter what url.

Broken by design?

**Comment by eXon** [comment]
I'll check that. It shouldn't be hard using a regex and the url.

**Comment by pgtaboada** [comment]
I looked into the code, changed:

videojs.Vimeo.canPlaySource = function(srcObj){
  if (srcObj.type)  
      return (srcObj.type == 'video/vimeo');
  else {
      var regExp = /^.*(vimeo\.com\/)((channels\/[A-z]+\/)|(groups\/[A-z]+\/videos\/))?([0-9]+)/;
      var match = srcObj.src.match(regExp);

      return (match)
  }
};

**Comment by Ragnarokkr** [comment]
+1. Same problem here. Cannot mix Youtube and Vimeo videos.

**Comment by pgtaboada** [comment]
Is it fixed?

**Comment by eXon** [comment]
There is a complete rewrite so you should try it

**Comment by nOurs88** [comment]
Hi @eXon 

I have the same problem. Impossible to mix correctly youtube and vimeo.

When I want to switch between providers I have 2 videos in same time.. Maybe I hace to remove html wrapper of iframe youtube/vimeo before to load a new video but i dont know if is the good way. Can you help me ? Thx

- videojs 5.10.4
- youtube plugin : https://github.com/videojs/videojs-youtube
- vimeo plugin: https://github.com/videojs/videojs-vimeo

Sample : http://loicjazon.com/tuto-videojs/ (sorry i cant put all on fiddle, have not https for all external resources :x)

And my main js :

```js
(function ($) {
    'use strict';
    var App = {
        myPlayer: null,
        myPlayerParams: {
            "controls": true,
            "autoplay": false,
            "preload": "auto",
            "techOrder": ["youtube", "vimeo"],
            "sources": [{
                "type": "video/youtube",
                "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"
            }]
        },
        init: function () {
            var that = this;
            that.myPlayer = videojs("#player", that.myPlayerParams, function () {
                console.log("VideoJS ready");
                that.myPlayer = this;
                that.loadCallToAction();
                that.play();
            });
        },
        loadCallToAction: function () {
            var that = this;
            $("[data-provider]").on("click", function () {
                var provider = $(this).attr('data-provider');
                var src      = $(this).attr('data-src');
                if (provider === 'youtube') {
                    that.loadYoutube(src);
                }
                if (provider === 'vimeo') {
                    that.loadVimeo(src);
                }
            });
        },
        play: function () {
            var that = this;
            $("#play").on("click", function () {
                that.myPlayer.play();
            });
        },
        loadYoutube: function (src) {
            var that = this;
            console.log('Inialisation loadYoutube(' + src + ')');
            that.myPlayer.src([{ "type": "video/youtube", "src": src}]);
            that.myPlayer.play();
        },
        loadVimeo: function (src) {
            var that = this;
            console.log('Inialisation loadVimeo(' + src + ')');
            that.myPlayer.src([{ "type": "video/vimeo", "src": src}]);
            that.myPlayer.play();
        }
    };
    $(document).ready(function () {
        App.init();
    });
})(jQuery);
```

Please, forgive my english !

**Comment by gkatsev** [comment]
Yeah, unfortunately, it's a known issue. We just fixed in videojs-youtube. We'll release it soon and also fixup videojs-vimeo with that as well.

**Comment by nOurs88** [comment]
hi @gkatsev 

Thx for your feedback ! Can you tell me how long before the release ? I would like to know if I have to try to fix it by myself meanwhile the releases ? Maybe next week ? :p

**Comment by gkatsev** [comment]
I hope to have a videojs-youtube release today.

**Comment by gkatsev** [comment]
videojs-youtube 2.1.0 is now out with a fix for the switching problem. videojs-vimeo may need a similar fix itself but that'll come after.

**Comment by nOurs88** [comment]
@gkatsev thx for your feedback

**Comment by prashantraval91185** [comment]
Can someone help me to resolve the issue when I try to switch between youtube and Vimeo or vice versa, play both videos at the same time, that means iframe wrapper div not replacing its append?
