### ISSUE TITLE
fullscreen event not triggering

### ISSUE THREAD

**Issue by Globegitter** [eXon/videojs-vimeo#16]
I have been trying to implement this plugin on my website now and while I can add event-listeners for 'play', 'pause', etc if I add one for 'fullscreenchange' it doesn't fire.
Any idea how that could be fixed?

Edit:
`$(document).on("webkitfullscreenchange mozfullscreenchange fullscreenchange", function());`
works though

**Comment by andreabr** [comment]
Hi, Globegitter,

Where should I put this code ?

Thanks,

André
