### ISSUE TITLE
Fullscreen in Chrome

### ISSUE THREAD

**Issue by tomul** [eXon/videojs-vimeo#43]
Hi,

I noticed that in Chrome, when you enter fullscreen, the vimeo player disappears, and the video just plays with the basic html5 player. Not sure if this is intended, but if you could share some light on this matter, i'd appreciate it. Example: http://jsbin.com/senodi/1/edit?html,js,output.

Thanks

**Comment by tomul** [comment]
As an update: I noticed that the iframe is generated without these attributes: webkitallowfullscreen mozallowfullscreen allowfullscreen. I added them to the iframe, using jquery, and now the vimeo controls are kept in fullscreen.

Thanks

**Comment by andreabr** [comment]
Hi Tomul,

Could you explain how to do this, please ?

Thank you so much,

André

**Comment by tomul** [comment]
Just select the iframe and add the attributes. Something like this:

```
  $('.embed-vjs.vimeo iframe').attr({
            webkitallowfullscreen: '',
            mozallowfullscreen: '',
            allowfullscreen: ''
          });
```
