### ISSUE TITLE
Vimeo poster image

### ISSUE THREAD

**Issue by nppsbh** [eXon/videojs-vimeo#51]
Hi.
Is it possible to use Vimeo video default image as poster like in the youtube plugin?
If poster not defined use video default image as poster.
Thanks
Really appreciate all the help.

**Comment by hendrathings** [comment]
New version has been release, YAY!
Yes, yes yes you can do by:

```
<video
    id="vid1"
    class="video-js vjs-default-skin"
    controls
    autoplay
    width="640" height="264"
    data-setup='{ "techOrder": ["vimeo"], "sources": [{ "type": "video/vimeo", "src": "https://vimeo.com/153979733"}], poster:"https://pbs.twimg.com/profile_images/863637334/doraemon.png" }'
  >
```
