### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by MichaelMcAlexander** [eXon/videojs-vimeo#58]
I can not get my vimeo and videojs to work properly. Can I please get a code example. Lets just say my vimeo video id is 123456789. How would I implement this? I really need help and have posted this question to numerous sites with no good answers. I dont want to have to use vimeos player. I have a vimeo pro $199/yr account so I can use videojs. I look at laracasts.com as an almost exact example of what I want to implement. please help.

Thanks
Mike
mcalexandems@vcu.edu

**Comment by eXon** [comment]
I'll take a look and shoot you a working example this week. This plugin has not been updated for a while.

**Comment by MichaelMcAlexander** [comment]
Thank you so much

**Comment by diogoreus** [comment]
I second that issue, having some problems with vimeo integration in the 4.X versions of video.js

**Comment by Magiweb** [comment]
@eXon I'm also having a lot of problems with this plugin not working. I'm using VideoJS version 5.7. Your youtube plugin works flawlessly, but using the exact same code to instantiate a vjs/vimeo player just breaks constantly. It looks like maybe a race issue? I'm getting this error: 

`
TypeError: a is undefined  - video.min.js (line 22, col 3904)   
TypeError: a is undefined video.min.js (line 22, col 3981)
`
Sometimes I get lucky and it loads, but most times it just doesn't, especially if I dynamically create a <video> tag using javascript and try to attach videojs/vimeo to that.

Would you be willing to help us resolve this? We're desperate to get this working by next Friday...
