### ISSUE TITLE
Video.js 5.0.2 and videojs-vimeo

### ISSUE THREAD

**Issue by Gorli** [eXon/videojs-vimeo#60]
Hello!

Should Video.js 5.0.2 work together with VideoJS-vimeo. I do not get out that it works.

Many thanks

ps: it works with VideoJS-youtube

**Comment by eXon** [comment]
This plugin has not been updated to VJS 5 and has no plan to do so in the near future. If you would like to contribute, PR are always welcome.

**Comment by chrisbaswell** [comment]
I noticed that you are maintaining the youtube pluging with the latest version of VideoJS.  Any particular reason why the Vimeo plugin isn't getting any updates?  Just wanted to know if there was a limitation with the Vimeo API or some other "difficult to overcome" reason.

**Comment by eXon** [comment]
Just lack of time. I barely have enough to update the YouTube one.

**Comment by eXon** [comment]
The last version is now working with VJS5.

**Comment by chrisbaswell** [comment]
Thanks!
