### ISSUE TITLE
Importing videojs-vimeo using ES6

### ISSUE THREAD

**Issue by howells** [eXon/videojs-vimeo#67]
I'm trying to import videojs-vimeo as an ES6 module, which works great with the videojs-youtube plugin but not this. I tried emulating the code in the videojs-youtube script but am not very very far! What do I need to do?

**Comment by eXon** [comment]
I need to make sure it is compatible with CommonJS / RequireJS. I'll try to fix it when I have a few minutes.

**Comment by howells** [comment]
That would be *amazing* :-) thanks

**Comment by eXon** [comment]
Should work if you use 2.0.1.

**Comment by howells** [comment]
Awesome! 

Only prob I'm getting now is `Uncaught ReferenceError: $ is not defined` on line 104; not sure how to get around that (sorry, am a noob)

**Comment by howells** [comment]
Sorry to chase, wondered if you knew what I might be doing wrong? I'm importing like so:

````
import $ from 'jquery'
import VideoJs from 'video.js'
import VideoJsYouTube from 'videojs-youtube'
import VideoJsVimeo from 'videojs-vimeo'
import Velocity from "velocity-animate"
import * as Config from "./config"
````
